### ISSUE TITLE
Not available on NPM

### ISSUE THREAD

**Issue by mtriff** [goto-bus-stop/sideshow#2]
This package is not found on NPM. Can it be re-published? And are you still maintaining this fork?

Thanks!

**Comment by goto-bus-stop** [comment]
I'm not really, sorry. I don't remember if it even works at this stage.

**Comment by mtriff** [comment]
No problem, thanks for the quick response. I decided to use [shipshapecode/shepherd](https://github.com/shipshapecode/shepherd) instead.
